image: Visual Studio 2017

platform:
  - x64

install:
  # Building Docker images
  - docker pull --platform linux ubuntu:xenial
  - docker pull --platform linux python:3.7.4-stretch
  - docker pull --platform linux node:8.15.1-slim
  - docker-compose -f ./docker-compose-int-test.yml build -m 8g


test_script:
  # Integration tests
  - docker-compose  -f ./docker-compose-int-test.yml run tester bash -c "sh /root/wait_pennai.sh && npm test"
  - docker-compose -f ./docker-compose-int-test.yml down
