image: Visual Studio 2017

install:
  # Building Docker images
  - docker-compose -f ./docker-compose-int-test.yml build -m 8g
test_script:
  # Integration tests
  - docker-compose  -f ./docker-compose-int-test.yml run tester bash -c "sh /root/wait_pennai.sh && npm test"
  - docker-compose -f ./docker-compose-int-test.yml down
